[package]
name = "snui"
version = "0.1.0"
authors = ["Eirik Tobiassen <eiriktob@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snew = {git = "https://github.com/Zower/snew", branch = "main"}
iced = "0.3.0"
iced_native = "0.4.0"