refresh_token = "aaaa"
immediate_posts = true
[binds]
k = "PostUp"
j = "PostDown" 
enter = "OpenPost" 
p = { action = "ToggleCollapse", modifiers = ["shift"] }
r = "OpenSubredditWindow"
l = "Login"
f = "Frontpage"
